site_name: Openfisca-france-indirect-taxation
nav:
  - Présentation: README.md
  - Sommaire : SUMMARY.md
  - Installation : Install_openfisca-france-indirect-taxation.md
  - Donnees:
    - Donnees sources:
      - Enquête Budgdet de famille (BdF) : Donnees/Budget_de_famille.md
      - Enquête Nationale Transports et déplacements (ENTD) : Donnees/Enquete_transport_et_deplacements.md
      - Enquête Logement (EnL) : Donnees/Enquete_logement.md
      - Enquête sur les revenus fiscaux et sociaux (ERFS) : Donnees/Enquête_revenus_fiscaux_et_sociaux.md
    - Construction :
      - Construction des données : Donnees/Construction.md
      - Appariemment : Donnees/Appariemment.md
      - Imputations de certaines dépenses : Donnees/Imputations.md
  - Simulations :
    - Présentation générale : Simulations/Presentation_generale.md
    - Legislation : Simulations/Legislation.md
    - Calage et vieillissement : Simulations/Calage_et_veillissement.md
    - Survey Scenario : Simulations/Survey_scenario.md
    - Exemple d'utilisation : Simulations/Exemple_utilisation.md